---
# Source: vault-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaop-vault-operator
  labels:
    helm.sh/chart: vault-operator-0.0.1
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/instance: vaop
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-operator
      app.kubernetes.io/instance: vaop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-operator
        app.kubernetes.io/instance: vaop
    spec:
      serviceAccountName: vault-operator
      securityContext:
        {}
      containers:
      - name: vault-operator
        securityContext:
            {}
        args:
        - --enable-leader-election
        command:
        - /manager
        image: "ghcr.io/finleap-connect/vaultoperator:0.0.1"
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: vault-operator-env
        - secretRef:
            name: vault-operator-creds
        ports:
        - containerPort: 443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        resources:
            null
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          secretName: vault-operator-cert
          defaultMode: 420
