apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
subjects:
- kind: ServiceAccount
  name: "vault-operator" # TODO: should include release.name
  namespace: "{{ .Release.Namespace }}"
