---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vault-finleap-cloud-v1alpha1-vaultsecret
  failurePolicy: Fail
  name: vvaultsecret.kb.io
  rules:
  - apiGroups:
    - vault.finleap.cloud
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vaultsecrets
  sideEffects: None
