# apiVersion: admissionregistration.k8s.io/v1beta1
# kind: MutatingWebhookConfiguration
# metadata:
#   name: mutating-webhook-configuration
#   annotations:
#     cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/vault-operator-cert'
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/vault-operator-cert'
