# The following patch adds a directive for helm to keep the crd on uninstall
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: vaultsecrets.vault.finleap.cloud
