apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vault-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "vault-operator.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
