apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-operator.fullname" . }}
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    {{- include "vault-operator.selectorLabels" . | nindent 4 }}