apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault-operator.serviceAccountName" . }}
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}