
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-operator.fullname" . }}-webhook
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    {{- include "vault-operator.selectorLabels" . | nindent 4 }}