namespace: "{{ .Release.Namespace }}"
namePrefix: "vault-operator-"
# namePrefix: "{{ .Release.Name }}-vault-operator-"

bases:
- ../webhook

patchesStrategicMerge:
- patches/webhookcainjection_patch.yaml

patchesJson6902:
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: vault-operator-validating-webhook-configuration
  path: patches/webhook_sideeffects_patch.yaml
