#!/usr/bin/env bash
set -euo pipefail

wd=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# download kubebuilder and install locally.
curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)
chmod +x kubebuilder && mv kubebuilder ${wd}
