#!/usr/bin/env bash
set -euo pipefail

export VAULT_VERSION="1.9.3"

wd=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
tmp_dir=$(mktemp -d)
function cleanup {
	rm -rf $tmp_dir
}
trap cleanup EXIT

# fetch Vault enterprise if possible
if [[ -z "${VAULT_ENTERPRISE_S3_ACCESS_KEY:-""}" ]]; then
	wget https://releases.hashicorp.com/vault/$VAULT_VERSION/vault_$VAULT_VERSION\_$(go env GOOS)_$(go env GOARCH).zip -O ${tmp_dir}/vault.zip
else
	wget "https://awscli.amazonaws.com/awscli-exe-$(go env GOOS)_$(go env GOARCH)-2.0.30.zip" -O "${tmp_dir}/awscliv2.zip"
	unzip -qq ${tmp_dir}/awscliv2.zip -d ${tmp_dir}
	${tmp_dir}/aws/install --install-dir ${tmp_dir}/aws-cli --bin-dir ${tmp_dir}/aws >/dev/null
	${tmp_dir}/aws/aws configure set aws_access_key_id $VAULT_ENTERPRISE_S3_ACCESS_KEY
	${tmp_dir}/aws/aws configure set aws_secret_access_key $VAULT_ENTERPRISE_S3_SECRET_KEY
	${tmp_dir}/aws/aws s3 cp s3://hc-enterprise-binaries/vault/prem.hsm/$VAULT_VERSION/vault-enterprise_$VAULT_VERSION+prem.hsm_linux_amd64.zip ${tmp_dir}/vault.zip
fi
unzip -o ${tmp_dir}/vault.zip -d ${wd}
