apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vaultsecrets.vault.finleap.cloud
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/vault-operator-cert'
spec:
  conversion:
    webhookClientConfig:
      service:
        name: vault-operator-webhook-service
  preserveUnknownFields: false

